### ISSUE TITLE
No internet in android

### ISSUE THREAD

**Issue by aicynide** [miru-project/bt-server#3]
2023/09/05 20:06:00.689941 app.go:55: [Error] Check dns failed[] lookup www.google.com on [::1]:53: read udp [::1]:55311->[::1]:53: read: connection refused
2023/09/05 20:06:00.883370 app.go:67: [Info] Check cloudflare dns[2a00:1450:4001:810::2004 216.58.206.36] <nil>

**Comment by MiaoMint** [comment]
Should be no problem,You can try playing a torrent

**Comment by aicynide** [comment]
Non-root android can't access /etc/resolv.conf so apply this patch https://github.com/termux/termux-packages/pull/9721

**Comment by aicynide** [comment]
Did you applied the patch?
